# Generated by Django 4.0.5 on 2022-06-17 07:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_remove_student_caddr_remove_student_cbirthday_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='cAddr',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AddField(
            model_name='student',
            name='cBirthday',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='student',
            name='cEmail',
            field=models.EmailField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='student',
            name='cPhone',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='student',
            name='cSex',
            field=models.CharField(default='M', max_length=2),
        ),
    ]
