# Generated by Django 4.0.5 on 2022-06-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_student_caddr_student_cbirthday_student_cemail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='listdata',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
